spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 367424355089-k0j4h7neeeaa34e1j7dma4q2ek42lgb0.apps.googleusercontent.com
            client-secret: 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

