spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: <Id>
            client-secret: <secretId>
          github:
            client-id: <Id>
            client-secret: <secretId>

